### ISSUE TITLE
5_model_learning

### ISSUE THREAD

**Issue by mehdimashayekhi** [TheophileMcgill/OptionsProject#1]
Hi I came across your implementation of Options and , I have a question about the model_learning part, in ```def _updateTables(self, reward, next_state):```,  can you please explain this part ```self.P[s1, o] -= alpha * self.P[s1, o]```? appreciate your response

**Comment by mehdimashayekhi** [comment]
never mind, I got it after looking at the paper, thanks anyways

**Comment by theophilegervet** [comment]
Glad to hear that, thanks for the interest in the repo!

Best,
Theo

Le dim. 26 mai 2019 à 14:59, Mehdi Mashayekhi <notifications@github.com> a
écrit :
